# Site settings
title: 히데쿠마 개발블로그
motto: 히데쿠마 개발블로그

email: d.hidekuma@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  python, python3, opencv, numpy, 표준편차, 파이썬, 가상환경, pyenv, virtualenv, aws, s3, apigateway, chalice, cloudfront, credential, git, docker, swarm, dynamodb, ec2, graphql, gitbash, lambda, pycurl, pythonic, serverless, vim, zappa, pep8
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://hidekuma.github.io"
github_username:  hidekuma
disqus_shortname: hidekuma

# Build settings
markdown: kramdown

google_analytics: UA-126032708-1

permalink: /:categories/:title/

feed:
  path: feed.xml

paginate: 5
paginate_path: "/page/:num/"
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
