title: hidekuma.github.io
description: Be awe$ome
author: Hidekuma
github: https://github.com/hidekuma
about: Love Python.
disqus_shortname: hidekuma
google_analytics: UA-126032708-1

enableTags: true
tagarray: []

permalink: /:categories/:title/

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/%ED%9A%8C%EC%9B%85-%EC%A0%95-367841180"
    #- icon: fa-stack-exchange
      #link: "#"
    - icon: fa-github
      link: "https://github.com/hidekuma"

#share:
  #twitter_username: github.io
  #fb_appid: 1749788565247320

urls:
    - text: About
      url: /about/
    #- text: Projects
      #url: /projects/
    #- text: Feed
      #url: /feed.xml

feed:
  path: feed.xml

url: "https://hidekuma.github.io"
baseurl: ""
paginate: 50
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
